#!/bin/bash

export CORE=${1}

# Create case 
touch ${PWD##*/}.foam

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Create fluid mesh
runApplication blockMesh
#runApplication changeDictionary 
runApplication checkMesh
runApplication renumberMesh -overwrite
#runApplication potentialFoam -writep

if [[ "$CORE" -gt 1 ]]
then
	# Run parallel
	runApplication decomposePar
	runParallel $(getApplication)
	#runApplication reconstructPar
	#rm -r processor*
else
	# Run serial
	runApplication $(getApplication)
fi
